sudo: required
dist: trusty
language: ruby

before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: nXHZBlIf4AaJuikffsjtzmWR07heoeh9TuYD734Q4UjdZubDAFUwhM+MHwBh4ey1I4w8UfKqpPQeNhUwXBqKJhTrrWHR3FkEkYPa7ZukRcFdEQMShJZdFBhxcheyrjCaAPdK16olcHI+hfKdWE0Thbm36KouNAZWS5iPdIzvup0QbZwxUFJOAHTbaNmNJtfOjxn6yoHYjt9ZcLqA39Yco/sC7rpzJKKgRV3TWjAp7qkBPgUbwPis2P4rFILZWqZbfw36BbnzTuAJiAqetDLCdBo2Tw0kjdjktlFsPIxcu7dnewqn78iPnvm2lS1UNOf7hR64m17Qp96vjONQffLDzSYwpqrqxkn4drGT8AEjU4wT7oBHb9hVEvuWIsUGUVzNHfjbklQes2L1xl4znANGh2vaN8znupLJV3WAtDHn4jShkM42nLGG6ICEOYfA5NoLvNda/ElgwIBvVhOAbHXkNfM7nwaWwCU3Wyf7W817Lf4HvHx4ecT5m+WGicYFT1RtaUCt5x8mzQWshim/PD/AY2vq/119ikTi+vL8QFekFhc3ZJvl7Ro6CD/RkCYm3ilC9qvQyWBle38yixYAHRefLPYa+PhYoZ/JTd4H6UaKv3YMzmZsrO7/jLoS27IeEiIKY8+DunpzK+vRhqcGfAwjxmgIn08heqIymByiBQD27YI=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  on:
    repo: GITenberg/Fair-Em_5137
    tags: true
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy